parserOptions:
  ecmaVersion: 2018

env:
  es6: true
  node: true
  jest: true

rules:
  max-len: ["warn", { "code": 120 }]
  comma-dangle: ["error", "always-multiline"]
  # object-curly-newline: ["error", "always"]
  # object-property-newline: ["error", { "allowAllPropertiesOnSameLine": true }]

ignorePatterns:
  '**/express/public/**/*.js'

extends: 'htmlacademy/node'